# SPDX-License-Identifier: MPL-2.0
name: OpenSSF Scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: '30 1 * * 1'
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  scorecard:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: hyperpolymath/standards/.github/workflows/scorecard-reusable.yml@c65436ee3351cd6b0fa14b142938b195efc77586
    secrets: inherit